services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: todo
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/todolist-backend:latest
    container_name: todo-backend
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/todolist-frontend:latest
    container_name: todo-frontend
    ports:
      - "80:4173"
    restart: unless-stopped

volumes:
  mysql_data:
